// Generated by scripts/generate.mjs; edit tokens/colors.json, not this file.
extension DesignTokens {
    static let table: [String: [Theme: RGBA]] = [
        "brand.graphite.accent": [.light: RGBA(validatedR: 31, g: 31, b: 31, a: 1), .dark: RGBA(validatedR: 237, g: 237, b: 237, a: 1)],
        "brand.graphite.on-accent": [.light: RGBA(validatedR: 238, g: 239, b: 242, a: 1), .dark: RGBA(validatedR: 23, g: 23, b: 23, a: 1)],
        "brand.ocean.accent": [.light: RGBA(validatedR: 10, g: 96, b: 153, a: 1), .dark: RGBA(validatedR: 110, g: 192, b: 247, a: 1)],
        "brand.ocean.on-accent": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "foundation.background": [.light: RGBA(validatedR: 238, g: 239, b: 242, a: 1), .dark: RGBA(validatedR: 23, g: 23, b: 23, a: 1)],
        "foundation.card": [.light: RGBA(validatedR: 246, g: 247, b: 248, a: 1), .dark: RGBA(validatedR: 27, g: 27, b: 27, a: 1)],
        "foundation.chart-blue": [.light: RGBA(validatedR: 73, g: 175, b: 243, a: 1), .dark: RGBA(validatedR: 110, g: 192, b: 247, a: 1)],
        "foundation.chart-green": [.light: RGBA(validatedR: 115, g: 214, b: 102, a: 1), .dark: RGBA(validatedR: 144, g: 223, b: 134, a: 1)],
        "foundation.chart-pink": [.light: RGBA(validatedR: 246, g: 121, b: 152, a: 1), .dark: RGBA(validatedR: 248, g: 145, b: 171, a: 1)],
        "foundation.danger": [.light: RGBA(validatedR: 173, g: 31, b: 31, a: 1), .dark: RGBA(validatedR: 236, g: 121, b: 121, a: 1)],
        "foundation.danger-foreground": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "foundation.foreground": [.light: RGBA(validatedR: 31, g: 31, b: 31, a: 1), .dark: RGBA(validatedR: 237, g: 237, b: 237, a: 1)],
        "foundation.info": [.light: RGBA(validatedR: 27, g: 71, b: 167, a: 1), .dark: RGBA(validatedR: 126, g: 170, b: 241, a: 1)],
        "foundation.info-foreground": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "foundation.muted-foreground": [.light: RGBA(validatedR: 102, g: 102, b: 102, a: 1), .dark: RGBA(validatedR: 161, g: 161, b: 161, a: 1)],
        "foundation.primary": [.light: RGBA(validatedR: 10, g: 96, b: 153, a: 1), .dark: RGBA(validatedR: 110, g: 192, b: 247, a: 1)],
        "foundation.primary-foreground": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "foundation.warning": [.light: RGBA(validatedR: 158, g: 87, b: 26, a: 1), .dark: RGBA(validatedR: 239, g: 178, b: 108, a: 1)],
        "foundation.warning-foreground": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "product.series.cobalt": [.light: RGBA(validatedR: 73, g: 175, b: 243, a: 1), .dark: RGBA(validatedR: 110, g: 192, b: 247, a: 1)],
        "product.series.leaf": [.light: RGBA(validatedR: 115, g: 214, b: 102, a: 1), .dark: RGBA(validatedR: 144, g: 223, b: 134, a: 1)],
        "product.series.rose": [.light: RGBA(validatedR: 246, g: 121, b: 152, a: 1), .dark: RGBA(validatedR: 248, g: 145, b: 171, a: 1)],
        "product.surface.canvas": [.light: RGBA(validatedR: 238, g: 239, b: 242, a: 1), .dark: RGBA(validatedR: 23, g: 23, b: 23, a: 1)],
        "product.surface.raised": [.light: RGBA(validatedR: 246, g: 247, b: 248, a: 1), .dark: RGBA(validatedR: 27, g: 27, b: 27, a: 1)],
        "product.text.primary": [.light: RGBA(validatedR: 31, g: 31, b: 31, a: 1), .dark: RGBA(validatedR: 237, g: 237, b: 237, a: 1)],
        "product.text.secondary": [.light: RGBA(validatedR: 102, g: 102, b: 102, a: 1), .dark: RGBA(validatedR: 161, g: 161, b: 161, a: 1)],
        "status.critical": [.light: RGBA(validatedR: 173, g: 31, b: 31, a: 1), .dark: RGBA(validatedR: 236, g: 121, b: 121, a: 1)],
        "status.info": [.light: RGBA(validatedR: 27, g: 71, b: 167, a: 1), .dark: RGBA(validatedR: 126, g: 170, b: 241, a: 1)],
        "status.on-critical": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "status.on-info": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "status.on-warning": [.light: RGBA(validatedR: 255, g: 255, b: 255, a: 1), .dark: RGBA(validatedR: 26, g: 26, b: 26, a: 1)],
        "status.warning": [.light: RGBA(validatedR: 158, g: 87, b: 26, a: 1), .dark: RGBA(validatedR: 239, g: 178, b: 108, a: 1)]
    ]
    static let brands: [String: [BrandRole: String]] = [
        "graphite": [.accent: "brand.graphite.accent", .onAccent: "brand.graphite.on-accent"],
        "ocean": [.accent: "brand.ocean.accent", .onAccent: "brand.ocean.on-accent"]
    ]
}
