import {readFileSync, mkdirSync, writeFileSync, existsSync} from 'node:fs';
import {resolve, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {resolveSource} from './source.mjs';
const root = fileURLToPath(new URL('../', import.meta.url));
const banner = '// Generated by scripts/generate.mjs; edit tokens/colors.json, not this file.\n';
const json = value => JSON.stringify(value, null, 2);

export function render(source) {
  const data = resolveSource(source), ids = Object.keys(data.colors);
  const series = ids.filter(id => id.startsWith('product.series.'));
  // Dot/hyphen flattening must never alias two CSS custom property names.
  const cssIDs = ids.map(id => id.replaceAll('.', '-'));
  if (new Set(cssIDs).size !== cssIDs.length) throw new Error('CSS id collision');
  const js = banner + `const data = ${json(data)};\n` + `
function freeze(value) {
  if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); }
  return value;
}
freeze(data);
export const schemaVersion = data.schemaVersion;
export const colorSpace = data.colorSpace;
export const tokenIDs = Object.freeze(Object.keys(data.colors));
export const seriesIDs = Object.freeze(tokenIDs.filter(id => id.startsWith('product.series.')));
export const brandIDs = Object.freeze(Object.keys(data.brands));
export function color(id, theme) {
  if (theme !== 'light' && theme !== 'dark') throw new Error('unknown theme: ' + theme);
  if (typeof id !== 'string' || !Object.hasOwn(data.colors, id)) throw new Error('unknown token: ' + String(id));
  return data.colors[id][theme];
}
export function brandColor(brand, role, theme) {
  if (typeof brand !== 'string' || !Object.hasOwn(data.brands, brand)) throw new Error('unknown brand: ' + String(brand));
  if (role !== 'accent' && role !== 'onAccent') throw new Error('unknown brand role: ' + role);
  return color(data.brands[brand][role], theme);
}
export function seriesColor(key, bindings, theme) {
  if (typeof key !== 'string' || !bindings || typeof bindings !== 'object' || Array.isArray(bindings) || !Object.hasOwn(bindings, key)) throw new Error('missing series binding: ' + String(key));
  const id = bindings[key];
  if (!seriesIDs.includes(id)) throw new Error('invalid series token: ' + id);
  return Object.freeze({id, color: color(id, theme)});
}
`;
  const dts = banner + `export type Theme = 'light' | 'dark';
export interface RGBA { readonly r:number; readonly g:number; readonly b:number; readonly a:number }
export type TokenID = ${ids.map(JSON.stringify).join(' | ')};
export type SeriesID = ${series.map(JSON.stringify).join(' | ') || 'never'};
export type BrandID = ${Object.keys(data.brands).map(JSON.stringify).join(' | ')};
export type BrandRole = 'accent' | 'onAccent';
export declare const schemaVersion: '1.0.0';
export declare const colorSpace: 'srgb';
export declare const tokenIDs: readonly TokenID[];
export declare const seriesIDs: readonly SeriesID[];
export declare const brandIDs: readonly BrandID[];
export declare function color(id:TokenID, theme:Theme): RGBA;
export declare function brandColor(brand:BrandID, role:BrandRole, theme:Theme): RGBA;
export declare function seriesColor(key:string, bindings:Readonly<Record<string,SeriesID>>, theme:Theme): Readonly<{id:SeriesID; color:RGBA}>;
`;
  const css = '/* Generated; namespaced data only, not a Basalt theme. */\n' + ['light','dark'].map(mode => `[data-lp-theme="${mode}"] {\n` + ids.map(id => {
    const {r,g,b,a} = data.colors[id][mode];
    return `  --lp-${id.replaceAll('.','-')}: rgba(${r}, ${g}, ${b}, ${a});`;
  }).join('\n') + '\n}').join('\n') + '\n' +
    '[data-lp-theme]:not([data-lp-theme="light"]):not([data-lp-theme="dark"]) {\n' +
    ids.map(id => `  --lp-${id.replaceAll('.', '-')}: initial;`).join('\n') + '\n}\n';
  const swiftColor = ({r,g,b,a}) => `RGBA(validatedR: ${r}, g: ${g}, b: ${b}, a: ${a})`;
  const swift = banner + `extension DesignTokens {
    static let table: [String: [Theme: RGBA]] = [
${ids.map(id => `        "${id}": [.light: ${swiftColor(data.colors[id].light)}, .dark: ${swiftColor(data.colors[id].dark)}]`).join(',\n')}
    ]
    static let brands: [String: [BrandRole: String]] = [
${Object.entries(data.brands).map(([name,m]) => `        "${name}": [.accent: "${m.accent}", .onAccent: "${m.onAccent}"]`).join(',\n')}
    ]
}
`;
  return {'dist/resolved.json':json(data)+'\n', 'dist/index.js':js, 'dist/index.d.ts':dts, 'dist/colors.ts':banner+`export const colors = ${json(data.colors)} as const;\n`, 'dist/colors.css':css, 'Sources/DesignTokens/GeneratedColors.swift':swift};
}

export function main(args) {
  let sourcePath = resolve(root,'tokens/colors.json'), out = root, check = false;
  for (let i=0; i<args.length; i++) {
    if (args[i] === '--check') check = true;
    else if (['--source','--out'].includes(args[i]) && args[i+1] && !args[i+1].startsWith('--')) {
      const flag = args[i++]; if (flag === '--source') sourcePath=resolve(args[i]); else out=resolve(args[i]);
    } else throw new Error(`unknown/incomplete argument: ${args[i]}`);
  }
  const outputs = render(JSON.parse(readFileSync(sourcePath,'utf8')));
  let drift = false;
  for (const [relative, content] of Object.entries(outputs)) {
    const path = resolve(out,relative);
    if (check) {
      if (!existsSync(path) || readFileSync(path,'utf8') !== content) {console.error(`generated drift: ${relative}`); drift=true;}
    } else {mkdirSync(dirname(path),{recursive:true}); writeFileSync(path,content);}
  }
  if (drift) throw new Error('generated outputs differ; run npm run generate');
  console.log(`${check ? 'Checked' : 'Generated'} ${Object.keys(outputs).length} outputs`);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {main(process.argv.slice(2));} catch(error) {console.error(error.message); process.exitCode=1;}
}
